### PR TITLE
fix: filter out empty names from email greetings (#52)

### LINKED ISSUE #52: Do not include empty names in the email
Image

### PR DESCRIPTION
**Pull request by preettrank53**
**Fixes #52**

### Description
This PR fixes an issue where email notifications included empty instructor names in the greeting, resulting in multiple consecutive commas like "Dear Harry Li, , , ,".

### Changes
- Modified `crs/packages/service/lib/notificationService.ts`
- Added filter to remove empty/whitespace-only names before joining instructor names

### Before
```typescript
const instructorNames = instructors.map((i) => i.name).join(", ");
```

### After
```typescript
const instructorNames = instructors
  .map((i) => i.name)
  .filter((name) => name && name.trim() !== "")
  .join(", ");
```
  
### Result

- Email greetings now display only valid instructor names
- Removes awkward formatting with multiple commas
- Handles edge cases:
  - `null`
  - `undefined`
  - Empty strings
  - Whitespace-only strings

### Testing

- ✅ Code compiles without errors  
- ✅ Maintains existing email functionality  
- ✅ Non-breaking change

### CODE REVIEW

File: packages/service/lib/notificationService.ts [hunk 1]
```diff
@@ -72,7 +72,10 @@ export class NotificationService {
     const student = await this.repos.user.requireUser(request.from);
 
     const instructorEmails = instructors.map((i) => i.email);
-    const instructorNames = instructors.map((i) => i.name).join(", ");
+    const instructorNames = instructors
+      .map((i) => i.name)
+      .filter((name) => name && name.trim() !== "")
+      .join(", ");
```
Comment (FlandiaYingman) [inline packages/service/lib/notificationService.ts]:
```suggestion
    const instructorNames = instructors
      .map((i) => i.name)
      .filter((name) => name !== "")
      .join(", ");
```
